# Generated by Django 2.0 on 2018-01-05 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20180105_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
    ]
